{
    'name': 'Cobrar con Tarjeta mediante STRIPE en Ecuador',
    'version': '17.0.1.0.0',
    'author': 'PJFlow.io',
    'website': 'https://pjflow.io',
    'category': 'Accounting/Payment Providers',
    'summary': 'Allows Stripe to work with Ecuadorian company by mapping EC to US for Stripe Connect.',
    'depends': ['payment_stripe'],
    'price': 29.99,
    'currency': 'USD',
    'license': 'LGPL-3',
    'images': ['static/description/images/cover.png'],
    'auto_install': False,
    'installable': True,
}
