{
    'name': 'Pagar con Crypto mediante Binance Pay en Odoo',
    'version': '17.0.1.0.0',
    'category': 'Accounting/Payment Providers',
    'summary': 'Accept cryptocurrency payments via Binance Pay',
    'description': 'Enable your customers to pay with 50+ cryptocurrencies '
                   '(USDT, BTC, ETH, BNB, etc.) using Binance Pay.',
    'author': 'PJFlow.io',
    'website': 'https://pjflow.io',
    'price': 79.99,
    'currency': 'USD',
    'license': 'LGPL-3',
    'depends': ['payment'],
    'data': [
        'views/payment_binance_templates.xml',
        'data/payment_method_data.xml',
        'data/payment_provider_data.xml',
        'views/payment_provider_views.xml',
        'data/payment_cron_data.xml',
    ],
    'images': ['static/description/images/cover.png'],
    'installable': True,
    'application': False,
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
}
